/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function AirportTopo(props) {
  const { nodes, materials } = useGLTF("/S10_Only_Topo_2022_2_Gltf.glb");
  return (
    <group {...props} dispose={null} scale={20} position={ [ 0, 2420, 0 ] }>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material #4"]}
        position={[-972, 75.14, -359.66]}
        rotation={[0, -1.57, 0]}
        scale={0.05}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Airfield.geometry}
        material={materials["Material #2146772860"]}
        position={[-1089.99, 50.85, -838.29]}
        scale={0.03}
      /> */}
    </group>
  );
}

useGLTF.preload("/S10_Only_Topo_2022_2_Gltf.glb");